blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('', views.index),
    path('tags/<slug:slug>/', views.tags),
    path('<slug:pk>/', views.article),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from mysite import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.Login.as_view()),
    path('logout/', LogoutView.as_view()),
    path('signup/', views.signup),
    path('mypage/', views.mypage),
    path('', views.index),
    path('blog/', include('blog.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Tag(models.Model):
  slug = models.CharField(primary_key=True,unique=True, max_length=20)
  name = models.CharField(unique=True, max_length=20)
  def __str__(self):
    return self.slug

class Article(models.Model):
  title = models.CharField(default="", blank=True, null=True, max_length=30)
  text = models.TextField(default="", )
  user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)
  count = models.IntegerField(default=0)
  tags = models.ManyToManyField(Tag, blank=True, through='ArticleTag')

class ArticleTag(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)  # 追加のフィールド

class Comment(models.Model):
  comment = models.TextField(default="", max_length=500)
  created_at = models.DateField(auto_now_add=True)
  user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
  article = models.ForeignKey(Article, on_delete=models.CASCADE)

mysite/models/account_models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
 
class UserManager(BaseUserManager):
 
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user
 
class User(AbstractBaseUser):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
 
    is_active = models.BooleanField(default=True)
 
    is_admin = models.BooleanField(default=False)
 
    objects = UserManager()
 
    USERNAME_FIELD = 'email'
 
    REQUIRED_FIELDS = []
 
    def __str__(self):
        return self.email
 
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True
 
    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True
    
    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_onetoone(sender, **kwargs):
    if kwargs['created']:
        from mysite.models.profile_models import Profile
        Profile.objects.create(user=kwargs['instance'])

mysite/models/profile_models.py
from django.db import models
from django.contrib.auth import get_user_model

class Profile(models.Model):
  user = models.OneToOneField(get_user_model(), primary_key=True, unique=True, on_delete=models.CASCADE)
  username = models.CharField(default="匿名ユーザ", max_length=30)
  zipcode = models.CharField(default="", max_length=8)
  prefecture = models.CharField(default="", max_length=6)
  city = models.CharField(default="", max_length=100)
  address = models.CharField(default="", max_length=200)

blog/forms.py
from django import forms
from blog.models import Comment

class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ('comment', )

mysite/forms.py
from django import forms
from mysite.models.profile_models import Profile
from django.contrib.auth import get_user_model
 
class UserCreationForm(forms.ModelForm):
  password = forms.CharField()

  class Meta:
    model = get_user_model()
    fields = ('email',)
  
  def clean_password(self):
    password = self.cleaned_data.get("password")
    return password

  def save(self, commit=True):
    user = super().save(commit=False)
    user.set_password(self.cleaned_data["password"])
    if commit:
        user.save()
    return user

class ProfileForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = (
      'username',
      'zipcode',
      'prefecture',
      'city',
      'address',
    )

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Article, Comment, Tag
from blog.forms import CommentForm
from django.core.paginator import Paginator

def index(request):
  objs = Article.objects.all().select_related('user__profile')
  paginator = Paginator(objs, 2)
  page_number = request.GET.get('page')
  context = {
    'title': 'ブログ一覧',
    'page_obj': paginator.get_page(page_number),
    'page_number': page_number
  }
  return render(request, 'blog/blogs.html', context)

def article(request, pk):
  
  obj = Article.objects.get(pk=pk)

  if request.method == 'POST':
    if request.POST.get('like_count', None):
      obj.count += 1
      obj.save()
    else:
      form = CommentForm(request.POST)
      if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.article = obj
        comment.save()

  comments = Comment.objects.filter(article=obj).select_related('user__profile')
  context = {
    'article': obj,
    'comments': comments
  }
  return render(request, 'blog/article.html', context)

def tags(request, slug):
  tag = Tag.objects.get(slug=slug)
  articles = tag.article_set.all().select_related('user__profile')
  paginator = Paginator(articles, 2)
  page_number = request.GET.get('page')
  context = {
    'title': '#タグ',
    'page_obj': paginator.get_page(page_number),
    'page_number': page_number
  }
  return render(request, 'blog/blogs.html', context)

mysite/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.views import LoginView
from blog.models import Article
from mysite.forms import UserCreationForm, ProfileForm
from django.contrib import messages
from mysite.models.profile_models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login

def index(request):
  ranks = Article.objects.order_by('-count')[:2]
  objs = Article.objects.all()[:3].select_related('user__profile')
  print(objs)
  context = {
    'title': 'Really Site',
    'articles': objs,
    'ranks': ranks,
  }
  # return HttpResponse('<h1>Really Site</h1>')
  return render(request, 'mysite/index.html', context)

# def login(request):
#   context = {}
#   if request.method == 'POST':
#     context['req'] = request.POST
#   return render(request, 'mysite/login.html', context)

class Login(LoginView):
  template_name = 'mysite/auth.html'

  def form_valid(self, form):
      messages.success(self.request, 'ログイン完了!!!')
      return super().form_valid(form)
  def form_invalid(self, form):
      messages.error(self.request, 'ログイン失敗!!!')
      return super().form_invalid(form)



def signup(request):
  context = {}
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save(commit=False)
      # user.is_active = False
      user.save()
      login(request, user)
      messages.success(request, '登録完了！！！')
      return redirect('/')
  return render(request, 'mysite/auth.html', context)

@login_required
def mypage(request):
  profile = Profile.objects.get(user=request.user)
  context = {'profile': profile}
  print(context)
  if request.method == 'POST':
    form = ProfileForm(request.POST)
    if form.is_valid():
      profile = form.save(commit=False)
      profile.user = request.user
      profile.save()
      messages.success(request, '更新が完了しましたよ')

  return render(request, 'mysite/mypage.html', context)

templates/blog/article.html
{% extends 'mysite/base.html' %} {% block content %}
<!-- prettier-ignore -->
<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 font-italic">{{article.title}}</h3>
      <p class="small text-muted text-right">
        {{ article.created_at }} {{ article.author }}
      </p>
      <p>{{article.text}}</p>
      <div>
        {% include 'mysite/snippets/like_count.html' %}<br />
        {% include 'mysite/snippets/tag.html' %}
      </div>
      <hr />
      {% include 'mysite/snippets/comment.html' %}
    </div>
    {% include 'mysite/snippets/sidebar.html' %}
  </div>
</main>

{% endblock %}

templates/blog/blogs.html
{% extends 'mysite/base.html' %} {% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 font-italic border-bottom">{{ title }}</h3>
      {% for obj in page_obj %}
      <div class="blog-post">
        <h2 class="blog-post-title">{{ obj.title }}</h2>
        <p class="blog-post-meta">
          {{ obj.created_at }} by
          <a href="#">{{ obj.user.profile.username }}</a>
        </p>
        <p>{{ obj.text }}</p>
        <a href="/blog/{{obj.id}}">続きはこちら</a>
      </div>
      <hr />
      {% endfor %} {% include 'mysite/snippets/pagination.html' %}
    </div>
    {% include 'mysite/snippets/sidebar.html' %}
  </div>
</main>

{% endblock %}

templates/mysite/auth.html
{% extends 'mysite/base_auth.html' %} {% block content %}
<div class="container">
  {% include 'mysite/snippets/messages.html' %}
  <div class="row">
    <div class="col-lg-3 m-auto">
      <h1 class="display-4 font-italic text-center">
        <a href="/" class="text-decoration-none">ReallySite</a>
      </h1>
    </div>
    <!-- prettier-ignore -->
    <div class="col-lg-3 m-auto">
      {% if user.is_authenticated %}
        ログイン中です
      {% else %}
        ログインしていません
      {% endif %}
      <form class="form-signin mx-4" method="POST">
        {% csrf_token %}
        <div class="text-center">
          <h1 class="h5 my-4">
            {% if 'login' in request.path %}
              ログイン
            {% else %}
              新規登録
            {% endif %}
          </h1>
        </div>

        <div class="form-label-group my-3">
          <input type="email"
            id="id_email"
            name="{% if 'login' in request.path %}username{% elif 'signup' in request.path %}email{% endif %}"
            class="form-control"
            placeholder="Email address"
            required
            autofocus />
        </div>

        <div class="form-label-group my-3">
          <input
            type="password"
            id="id_password"
            name="password"
            class="form-control"
            placeholder="Password"
            required
          />
        </div>

        <button class="btn btn-primary btn-block my-3" type="submit">
          サインイン
        </button>
      </form>
      {% if "login" in request.path %}
        <div class="text-center">
            <a href="/signup/" class="link-secondary">新規登録はこちら</a>
        </div>
      {% elif "signup" in request.path %}
        <div class="text-center">
          <a href="/login/" class="link-secondary">ログインはこちら</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/mysite/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% include 'mysite/snippets/head.html' %}
  </head>
  <body>
    <!-- prettier-ignore -->
    {% include 'mysite/snippets/header.html'%}
    {% include 'mysite/snippets/messages.html'%}
    {% block content %} {% endblock %}
  </body>
</html>

templates/mysite/base_auth.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    {% include 'mysite/snippets/head.html' %}
  </head>
  <!-- prettier-ignore -->
  <body class="vh-100 d-flex align-items-center justify-content-center bg-light">
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/mysite/index.html
{% extends 'mysite/base.html' %} {% block content %}

<div class="container">
  <div class="p-4 p-md-5 mb-4 rounded bg-warning">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">Django講座</h1>
      <p class="lead my-3">文章をかこう</p>
      <p class="lead mb-0">
        <a href="#" class="font-weight-bold">続きを読む</a>
      </p>
    </div>
  </div>
  <div class="row mb-2">
    {% for obj in ranks %}
    <div class="col-md-6">
      <div
        class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative"
      >
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Django</strong>
          <h3 class="mb-0">{{obj.title}}</h3>
          <div class="mb-1 text-muted">{{obj.created_at}}</div>
          <p class="card-text mb-auto">{{obj.text}}</p>
          <a href="/blog/{{obj.id}}" class="stretched-link">続きを読む</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 font-italic border-bottom">Django Lesson</h3>
      {% for obj in articles %}
      <div class="blog-post">
        <h2 class="blog-post-title">{{ obj.title }}</h2>
        <p class="blog-post-meta">
          {{ obj.created_at }} by
          <a href="#">{{ obj.user.profile.username }}</a>
        </p>
        <p>{{ obj.text }}</p>
        <a href="/blog/{{obj.id}}">続きはこちら</a>
      </div>
      <hr />
      {% endfor %}
      <nav class="blog-pagination">
        <a class="btn btn-outline-primary" href="/blog/">ブログ一覧はこちら</a>
      </nav>
    </div>
    {% include 'mysite/snippets/sidebar.html' %}
  </div>
</main>

{% endblock %}

templates/mysite/mypage.html
{% extends 'mysite/base.html' %} {% block content %}

<main class="container">
  <div class="row">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 font-italic border-bottom">マイページ</h3>
      <form class="row g-3" method="POST">
        {% csrf_token %}
        <div class="col-12">
          <label class="form-label">ユーザー名（公開されます）</label>
          <input
            type="text"
            class="form-control"
            id="id_username"
            name="username"
            value="{{user.profile.username}}"
            placeholder="煉獄 杏寿郎"
          />
        </div>

        <div class="col-md-2">
          <label class="form-label">郵便番号</label>
          <input
            type="text"
            class="form-control"
            id="id_zipcode"
            name="zipcode"
            value="{{user.profile.zipcode}}"
          />
        </div>
        <div class="col-md-4">
          <label class="form-label">都道府県</label>
          <select id="id_prefecture" name="prefecture" class="form-select">
            <option selected>選択...</option>
            <option>...</option>
          </select>
        </div>
        <div class="col-md-6">
          <label class="form-label">市区</label>
          <input
            type="text"
            class="form-control"
            id="id_city"
            name="city"
            value="{{user.profile.city}}"
          />
        </div>

        <div class="col-12">
          <label class="form-label">住所</label>
          <input
            type="text"
            class="form-control"
            id="id_address"
            name="address"
            placeholder=""
            value="{{user.profile.address}}"
          />
        </div>

        <div class="col-12">
          <button type="submit" class="btn btn-success">保存</button>
        </div>
      </form>
    </div>

    {% include 'mysite/snippets/sidebar.html' %}
  </div>
</main>

{% endblock %}

templates/mysite/snippets/comment.html
<div>
  <h3 class="h6">コメント</h3>
  <div class="list-group">
    {% for comment in comments %}
    <a class="list-group-item list-group-item-action p-3 rounded-0">
      <p class="m-0"><small>{{comment.comment}}</small></p>
      <p class="m-0">
        <small>
          {{comment.user.profile.username}}さん {{comment.created_at}}
        </small>
      </p>
    </a>
    {% endfor %}
  </div>
  <!-- prettier-ignore -->
  {% if user.is_authenticated %}
  <form method="POST" class="my-4">
    {% csrf_token %}
    <div class="mb-2">
      <label></label>
      <textarea
        name="comment"
        class="rounded-0 bg-light form-control"
        rows="3"
      ></textarea>
    </div>
    <div class="text-right">
      <button class="btn btn-sm btn-outline-success" type="submit">
        コメントする
      </button>
    </div>
  </form>
  {% else %}
  <p class="my-4">
    コメントを投稿するには<a href="/login/">ログイン</a>してください
  </p>
  {% endif %}
</div>

templates/mysite/snippets/footer.html
<footer class="border-top py-5 text-center bg-light mt-4">
  <p>
    <a href="/">トップに戻る</a>
  </p>
</footer>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
  integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
  crossorigin="anonymous"
></script>

templates/mysite/snippets/head.html
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<!-- Bootstrap CSS -->
<!-- レクチャー時点のalpha版を使用しています。betaや安定版を使用する場合はcssクラスが変更になっている可能性がありますので、適時修正してください -->
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
  integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I"
  crossorigin="anonymous"
/>
<title>ReallySite</title>

templates/mysite/snippets/header.html
<header class="py-3">
  <div class="row flex-nowrap justify-content-center align-item-center">
    <div class="col-4 text-center">
      <h1 class="display-4 font-italic">
        <a href="/" class="text-decoration-none">ReallySite</a>
      </h1>
    </div>
  </div>
</header>
<div class="py-1 mb-2">
  <nav class="nav d-flex justify-content-between">
    <a class="p-2 link-secondary" href="/blog/">ブログ</a>
    <a class="p-2 link-secondary" href="#">お問い合わせ</a>
    {% if user.is_authenticated %}
    <div>
      <a class="p-2 link-secondary" href="/mypage/">マイページ</a>
      <a class="p-2 link-secondary" href="/logout/">ログアウト</a>
    </div>
    {% else %}
    <div>
      <a class="p-2 link-secondary" href="/login/">ログイン</a>
      <a class="btn btn-outline-info" href="/signup/">新規登録</a>
    </div>
    {% endif %}
  </nav>
</div>

templates/mysite/snippets/like_count.html
<form method="POST" class="d-inline">
  {% csrf_token %}
  <input type="hidden" name="like_count" value="true" />
  <button type="submit" class="btn btn-sm btn-outline-warning">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      fill="currentColor"
      class="bi bi-lightning-fill"
      viewBox="0 0 16 16"
    >
      <path
        fill-rule="evenodd"
        d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"
      />
    </svg>
    {{ article.count }} good
  </button>
</form>

templates/mysite/snippets/messages.html
{% for msg in messages %}
<nav class="py-2 {{msg.tags}}">
  <div class="container">{{msg}}</div>
</nav>
{% endfor %}

templates/mysite/snippets/pagination.html
<nav class="blog-pagination">
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a class="btn btn-outline-primary" href="?page=1">&laquo; first</a>
      <a
        class="btn btn-outline-primary"
        href="?page={{ page_obj.previous_page_number }}"
        >previous</a
      >
      {% endif %} {% if page_obj.has_next %}
      <a
        class="btn btn-outline-primary"
        href="?page={{ page_obj.next_page_number }}"
        >next</a
      >
      <a
        class="btn btn-outline-primary"
        href="?page={{ page_obj.paginator.num_pages }}"
        >last &raquo;</a
      >
      {% endif %}
    </span>
  </div>
</nav>

templates/mysite/snippets/sidebar.html
<aside class="col-md-4">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">ふじサンについて</h4>
    <p class="mb-0">ようこそMy講座へ！</p>
  </div>
</aside>

templates/mysite/snippets/tag.html
{% for tag in article.tags.all %}
<a
  href="/blog/tags/{{ tag.slug }}/"
  class="btn btn-sm btn-outline-secondary mt-2"
>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="16"
    height="16"
    fill="currentColor"
    class="bi bi-tag-fill"
    viewBox="0 0 16 16"
  >
    <path
      d="M2 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 6.586 1zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"
    />
  </svg>
  {{ tag.name }}
</a>
{% endfor %}